refactor: standalone app and control flow
czeckd/angular-svg-icon pull request #151
Opened 2023-11-14 17:33 UTC by sheikalthaf

2023-11-14 17:35 UTC, sheikalthaf commented
@czeckd this is not an update for library, just converted the demo app to standalone and using control flow

2023-11-15 04:24 UTC, czeckd requested changes
@sheikalthaf Found a typo, but other than that it looks good. Thanks for the update!

2023-11-15 04:24 UTC, czeckd commented on src/app/demo-app.component.html
> +			@if (!autoheight) {
This should be `!autowidth`.

2023-11-15 05:30 UTC, sheikalthaf commented on src/app/demo-app.component.html
> +			@if (!autoheight) {
fixed it

2023-11-16 10:11 UTC, sheikalthaf commented
@czeckd fixed the typo

2023-11-16 19:41 UTC, merged