Universal compatibility
czeckd/angular-svg-icon pull request #57
Opened 2018-11-12 05:31 UTC by edulelis

When using this package with Angular Universal it will log errors on the server as `document` is not available server-side. Also, preloading the SVGs server-side have no advantage.

The changes to be compatible with Angular Universal are in summary:
- Avoid SVG requests server-side.
- Wrap code the uses or modifies the DOM to run in the browser only.

2018-11-13 07:27 UTC, czeckd commented
Wouldn't having the svgs loaded on the server side be desirable for search engine optimization or meta cards?

2018-11-14 04:11 UTC, edulelis commented
Yes, you are right.
However, the problem with loading them server-side (and keep a single codebase) is the inability to cast them to an SVG Element, .i.e., doing this code server-side.
```
const div = document.createElement('DIV');
div.innerHTML = svg;
return <SVGElement>div.querySelector('svg');`
```
The only way I found so far using a single codebase is using `this.renderer.createElement('svg')` to create a pristine element and perform subsequent calls to manually extract and parse the attributes and children of the SVG string to this new element, but I don't think this approach is good.

The best approach I found (given the current angular universal config) would be having two codebases with a simpler server only version. The server version would only treat the SVGs as pure strings and inject them binding to the property innerHTML as in `<element [innerHTML]="svg"></element>".  
Changing the stretch property would still need to be done by string manipulations if to be performed server-side (but I think this step is unnecessary).

Currently Angular Universal does this replacement of files with a config in the `angular.json`,  for example, with environment files:

```
"server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts", <-
                  "with": "src/environments/environment.prod.ts" <-
                }
              ]
            }
          }
        }
```

The downside of this approach is that this config is for angular-cli only projects.
Those with webpack would have to perform the replacement themselves.

Do you think this is a good approach?

2018-11-15 05:29 UTC, czeckd commented
By two codebases do you mean literally two code bases, or do you mean two flows in the lib/src/svg-icon-registry.service.ts? So, keep the code as is in the pull request guarded by `isPlatformBrowser(this.platformId)` and if not, treat SVGs as pure strings and inject them into the HTML as you propose?

2018-11-15 06:44 UTC, edulelis commented
I mean two code bases, but for the service only.
I've been taking a look at how other libs treat the server-side rendering part, as in `https://github.com/salemdar/ngx-cookie`.
With Angular Universal there is an AppServerModule that can be used to provide an alternative service class, so the two implementations (service only) could stay separated. I'm still not sure how to inject the retrieved SVG string as HTML server-side while keeping the component consistent.
I will do some testing with this and get back with the results.

2018-11-15 19:47 UTC, edulelis commented
Good news!

I dug deeper to find a simpler way and make less changes to the code.
I changed the way the services is imported as suggested by the Angular 6 docs to define singletons: `https://angular.io/guide/singleton-services`.

The only caveat of the for the server is the need to provide a base url for relative request paths.
In my tests I added it in the AppServerModule:
```
[...]
  bootstrap: [AppComponent],
  providers: [{provide: 'SERVER_URL', useValue: 'http://localhost:4000/'}] <---
})
```

Please take a look at the code and give me your thoughts.

2018-11-17 06:10 UTC, czeckd commented
It looks like from reading over the code that the SERVER_URL would only be necessary if using Universal though, right? If so, that seems a reasonable tradeoff to be able to use the svgs, right.

2018-11-17 06:22 UTC, czeckd commented
Also, why get rid of the SVG_ICON_REGISTRY_PROVIDER and factory? The service was modeled after the [icon-registry](https://github.com/angular/material2/blob/master/src/lib/icon/icon-registry.ts) of Material.

2018-11-18 20:29 UTC, edulelis commented
Yes, the SERVER_URL is only needed server-side.
I was banging my head to find how to inject the dependencies on SVG_ICON_REGISTRY_PROVIDER.
With help from the link you posted I got it working and restored the code from the provider.

2018-11-20 09:22 UTC, czeckd commented
Thank you for all the work on this. It looks pretty much good-to-go.

Can you please do one final thing? Please do `npm run lint` and fix anything that might come up? There looks to be a couple of lines that only have formatting changes.

2018-11-20 23:57 UTC, edulelis commented
Done :+1:.

2018-11-21 00:48 UTC, czeckd requested changes
Thanks. Last two changes/questions. Also, did you want to update the docs or did you want me to do that?

2018-11-21 00:48 UTC, czeckd commented on lib/src/svg-icon-registry.service.ts
> +	providedIn: 'root',
Is the `providedIn` still needed? I do not believe so since the service has a factory/provider instead.

2018-11-21 00:48 UTC, czeckd commented on lib/src/svg-icon.component.ts
> -
Since no code changed, please add back in line.

2018-11-22 02:22 UTC, edulelis commented on lib/src/svg-icon-registry.service.ts
> +	providedIn: 'root',
Indeed, this is not needed, I'll remove it.

2018-11-22 02:24 UTC, edulelis commented
I'll draft the docs. Is there anything else worth mentioning beyond providing the SERVER_URL server-side?

2018-11-23 09:42 UTC, czeckd approved these changes

2018-11-23 23:54 UTC, merged

2018-11-24 00:16 UTC, czeckd commented
Thanks again for your work on this. v7.0.0 with your work to support Universal now should be available on npm.